addTexture("tank-panther", "./assets/images/tank-panther-right.png");
addTexture("chopper", "./assets/images/chopper.png");
addTexture("box", "./assets/images/box.png");
addTexture("box2", "./assets/images/box2.png");
addTexture("bullet", "./assets/images/bullet.png");
addTexture("dawn_like_floor0", "./assets/tilemaps/dawn_like_floor.png");
addTexture("dawn_like_door0", "./assets/tilemaps/dawn_like_door0.png");
addTexture("radar", "./assets/images/radar.png");
addTexture("wall", "./assets/tilemaps/wall.png");
